name: deploy
on:
  push:
    branches: [ "main" ]

jobs:
  # ...existing code...
  first-job:
    runs-on: ubuntu-latest

    strategy:
      #fail-fast: false
      matrix:
        message: [ "Hola", "Mundo", "Bootcamp Github Action" ]

  steps:
  - name: Print message
    run: echo "${{ matrix.message }}"
      