name: deploy
on: 
  push:
    branches: ["main"]

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Hello World
              uses: actions/checkout@v4

            - name: Run a script
              run: echo "This is the first job"

    second-job:
        if: ${{ github.ref == 'refs/heads/main' }}
        needs: first-job
        runs-on: ubuntu-latest
        steps:
            - name: Hello World
              uses: actions/checkout@v4

            - name: Run a script
              run: echo "This is the second job"
