name: deploy
on: 
  push:
    branches: ["main"]

jobs:
    first-job:
        runs-on: ubuntu-latest

        env: 
        Name: Codigofacilito

        steps:
             - name: Run a script
               run: echo "Hello World, $Name"

    second-job:
        if : ${{ github.ref == 'refs/heads/main' }}
        runs-on: ubuntu-latest
        steps:
            - name: Hello World
              uses: actions/checkout@v4

            - name: Run a script
              run: echo "This is the second job"
