name: deploy
on: 
  push:
    branches: ["main"]

jobs:
    first-job:
        runs-on: ubuntu-latest

        env: 
         NAME: Codigofacilito

        # ...existing code...
        steps:
          - name: working dir
            run: ls -al
        # ...existing code...
          - name: Action
            uses: actions/checkout@v4
          
          - name: working dir after Action
            run: ls -al

    second-job:
        needs: first-job
        runs-on: ubuntu-latest
        steps:
            - name: Hello World
              run: echo "Hello World"
