name: deploy
on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Hello World
              uses: actions/checkout@v4

            - name: Run a script
              run: echo "This is the first job"