name: deploy
on: 
  push:
    branches: ["main"]

jobs:
    first-job:
        runs-on: ubuntu-latest

        env: 
         NAME: Codigofacilito

        # ...existing code...
        steps:
          - name: Hello World
            run: echo "Hello World, $NAME"
        # ...existing code...

    second-job:
        needs: first-job
        runs-on: ubuntu-latest
        steps:
            - name: Hello World
              run: echo "Hello World"
