name: deploy
on: 
  push:
    branches: ["main"]

jobs:
    # ...existing code...
    first-job:
        runs-on: ubuntu-latest
        steps:
          - name: working dir
            id: step_1
            run: echo "my_variable=Hello World" >> $GITHUB_OUTPUT

          - name: Obtener mensaje
            run: echo "${{ steps.step_1.outputs.my_variable }}"
# ...existing code...
    second-job:
        needs: first-job
        runs-on: ubuntu-latest
        steps:
            - name: Hello World
              run: echo "Hello World"
